apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapi
  labels:
    app: feedapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedapi
  template:
    metadata:
      labels:
        app: feedapi
    spec:
      containers:
      - name: u-feed-api
        image: harunrst/u-feed-api
        ports:
        - containerPort: 80
        livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15